export type UserId = string;
export type GroupId = string;
export type TripId  = string;

export interface User {
  id: UserId;
  name: string;
  initials: string;
  email?: string;
  avatarKey: 'c' | 'j' | 'm' | 'r' | 'f' | 's' | 'ai';
}

export type TripStatus = 'Active' | 'Planning' | 'Idea';

export interface TripSummary {
  id: TripId;
  dest: string;
  when: string;
  status: TripStatus;
  tint: string;
  ready: boolean;
}

export type GroupVibe = 'cozy' | 'adventure' | 'romantic' | 'city' | 'beach';
export type GroupPace = 'chill' | 'balanced' | 'packed';
export type GroupBudgetLevel = 'shoestring' | 'comfortable' | 'treat';

export interface GroupPrefs {
  vibe?: GroupVibe;
  pace?: GroupPace;
  budget?: GroupBudgetLevel;
  interests: string[];
  notes?: string;
}

export interface Group {
  id: GroupId;
  name: string;
  members: UserId[];
  invited: string[];
  inviteCode: string;
  tint: string;
  trips: TripSummary[];
  prefs: GroupPrefs;
}

export interface Trip {
  place: string;
  tagline: string;
  dates: { label: string; year: number; nights: number };
  countdown: number;
  hero: { label: string; tint: string };
}

export interface DateOption {
  id: string;
  range: string;
  sub: string;
  note?: string;
  weather?: string;
  proposedBy: UserId;
  votes: UserId[];
  startDate?: string; // ISO yyyy-mm-dd
  endDate?: string;
}

export type BoardItemKind = 'idea' | 'note' | 'photo';

export interface BoardItem {
  id: string;
  kind: BoardItemKind;
  title: string;
  note?: string;
  tint: string;
  who: UserId;
  imageUrl?: string;
}

export interface BoardItemInput {
  kind: BoardItemKind;
  title: string;
  note?: string;
  tint: string;
  imageFile?: File;
}

// A destination suggestion generated by the AI for any trip (as opposed to
// the seeded Lombok demo catalog referenced by cardIds).
export interface AiSuggestion {
  title: string;
  area: string;
  detail: string;
  price?: string;
  kind: 'stay' | 'eat' | 'activity' | 'travel';
  /** Suggested start time, "HH:mm" 24h. */
  time?: string;
  /** Approximate WGS84 coordinates of the place. */
  lat?: number;
  lng?: number;
}

// ── Events: lightweight single-date outings proposed to the group ────────────

export interface EventPart {
  id?: string;        // absent for parts not yet saved
  title: string;
  time?: string;
  venue?: string;
  venueUrl?: string;
  ticketUrl?: string;
}

export interface GroupEvent {
  id: string;
  title: string;
  date?: string;      // ISO yyyy-mm-dd
  time?: string;      // free text, e.g. "7pm"
  note?: string;
  venue?: string;
  venueUrl?: string;
  ticketUrl?: string;
  tint: string;
  who: UserId;
  going: UserId[];
  parts: EventPart[];
}

export interface EventInput {
  title: string;
  date?: string;
  time?: string;
  note?: string;
  venue?: string;
  venueUrl?: string;
  ticketUrl?: string;
  parts?: EventPart[];
}

export interface EventsApi {
  list(groupId: string): Promise<GroupEvent[]>;
  add(groupId: string, input: EventInput): Promise<void>;
  update(eventId: string, input: EventInput): Promise<void>;
  rsvp(eventId: string, going: boolean): Promise<void>;
  remove(eventId: string): Promise<void>;
}

// ── Trip photos: shared gallery, private to the group ────────────────────────

export interface TripPhoto {
  id: string;
  /** Display URL — short-lived signed URL (Supabase) or object URL (demo). */
  url: string;
  caption?: string;
  who: UserId;
  at: string;
}

export interface PhotosApi {
  list(tripId: string): Promise<TripPhoto[]>;
  add(tripId: string, groupId: string, file: File, caption?: string): Promise<void>;
  remove(photoId: string): Promise<void>;
}

// ── Booking documents: confirmations (PDFs/images) shared with the group ─────

export interface TripDoc {
  id: string;
  name: string;
  /** Short-lived signed URL (Supabase) or object URL (demo). */
  url: string;
  mime?: string;
  /** Who the booking covers; empty array = the whole group. */
  memberIds: UserId[];
  /** The plan item (activity card) this confirmation is attached to. */
  itemId?: string;
  who: UserId;
  at: string;
}

export interface DocInput {
  name: string;
  memberIds: UserId[];
  itemId?: string;
}

export interface DocsApi {
  list(tripId: string): Promise<TripDoc[]>;
  add(tripId: string, groupId: string, file: File, input: DocInput): Promise<void>;
  remove(docId: string): Promise<void>;
}

// ── Chat: message threads on a trip or an event ───────────────────────────────

export interface ChatMsg {
  id: string;
  who: UserId;
  body: string;
  at: string;
}

export interface ChatScope {
  groupId: string;
  tripId?: string;
  eventId?: string;
}

export interface ChatApi {
  list(scope: ChatScope): Promise<ChatMsg[]>;
  send(scope: ChatScope, body: string): Promise<void>;
}

// Injected per environment: real Supabase implementation when configured,
// in-memory demo implementation otherwise.
export interface DatesApi {
  list(tripId: string): Promise<DateOption[]>;
  propose(tripId: string, input: { start: string; end: string; note?: string }): Promise<void>;
  vote(optionId: string): Promise<void>;
  unvote(optionId: string): Promise<void>;
  remove(optionId: string): Promise<void>;
}

export interface BoardApi {
  list(tripId: string): Promise<BoardItem[]>;
  add(tripId: string, groupId: string, input: BoardItemInput): Promise<void>;
  remove(itemId: string): Promise<void>;
}

export type DiscoverCat = 'stay' | 'eat' | 'see' | 'culture';
export type DiscoverKind = 'stay' | 'eat' | 'activity';

export interface DiscoverCard {
  id: string;
  cat: DiscoverCat;
  kind: DiscoverKind;
  title: string;
  area: string;
  price: number;
  per: string;
  duration?: string;
  rating?: number;
  tint: string;
  label: string;
  why: string;
}

export interface CultureCard {
  id: string;
  title: string;
  area: string;
  intro: string;
  tips: Array<{ do: boolean; t: string }>;
}

export interface DiscoverData {
  cards: DiscoverCard[];
  culture: CultureCard;
  filters: Array<{ id: string; label: string }>;
  prompts: string[];
}

export type ItineraryItemCat = 'travel' | 'stay' | 'food' | 'beach' | 'activity';

export interface LatLng {
  lat: number;
  lng: number;
}

export interface ItineraryItem {
  id: string;
  /** Minutes since midnight (0–1439), or null when not yet scheduled. See lib/time.ts. */
  time: number | null;
  title: string;
  place: string;
  url?: string;
  cat: ItineraryItemCat;
  who: UserId;
  coords?: LatLng;
  /** ISO date the range ends: check-out for stays, return for flights. */
  endDate?: string;
  likes: number;
  liked: boolean;
  comments: number;
}

export interface Day {
  id: string;
  n: number;
  /** Display label, e.g. "Oct 3". */
  date: string;
  /** Real calendar date, ISO yyyy-mm-dd (missing on older data). */
  iso?: string;
  title: string;
  area: string;
  items: ItineraryItem[];
}

export interface ItineraryItemInput {
  /** "HH:mm" from <input type="time">. */
  time?: string;
  title: string;
  place?: string;
  cat: ItineraryItemCat;
  url?: string;
  lat?: number;
  lng?: number;
  /** ISO date: check-out (stay) or return (travel). */
  endDate?: string;
}

export interface ItineraryApi {
  listDays(tripId: string): Promise<Day[]>;
  setupDays(tripId: string, groupId: string, start: string, end: string): Promise<void>;
  addItem(dayId: string, input: ItineraryItemInput): Promise<void>;
  updateItem(itemId: string, input: ItineraryItemInput): Promise<void>;
  removeItem(itemId: string): Promise<void>;
  toggleLike(itemId: string, liked: boolean): Promise<void>;
}

export type StayStatus = 'todo' | 'pending' | 'booked';

export interface Stay {
  id: string;
  title: string;
  area?: string;
  cost?: number;
  status: StayStatus;
  who: UserId | null;
  url?: string;
}

export interface StaysApi {
  list(tripId: string): Promise<Stay[]>;
  add(tripId: string, groupId: string, input: { title: string; area?: string; cost?: number; status: StayStatus; url?: string }): Promise<void>;
  update(stayId: string, input: { title: string; area?: string; cost?: number; url?: string }): Promise<void>;
  setStatus(stayId: string, status: StayStatus): Promise<void>;
  remove(stayId: string): Promise<void>;
}

export type SideTripType = 'solo' | 'open';

export interface SideTrip {
  id: string;
  title: string;
  host: UserId;
  when: string;
  place: string;
  type: SideTripType;
  going: UserId[];
  cap?: number;
  note?: string;
}

export interface PackingItem {
  id: string;
  item: string;
  who: UserId;
  done: boolean;
}

export interface PackingList {
  id: string;
  name: string;
  items: PackingItem[];
}

export type BookingStatus = 'booked' | 'pending' | 'todo';

export interface Booking {
  id: string;
  title: string;
  meta: string;
  cost?: number;
  status: BookingStatus;
  who: UserId | null;
  ref?: string;
  from?: 'email';
  files: string[];
}

export interface BudgetCat {
  name: string;
  spent: number;
  color: string;
}

export interface Budget {
  total: number;
  spent: number;
  currency: string;
  cats: BudgetCat[];
  importEmail: string;
  bookings: Booking[];
}

export interface FeedEvent {
  id: string;
  who: UserId;
  action: 'added' | 'booked' | 'commented';
  what: string;
  to?: string;
  when: string;
  react?: number;
}

export type BudgetView = 'split' | 'joint';
export type PlanTab = 'itinerary' | 'sidetrips' | 'packing' | 'board';
export type AppTab = 'home' | 'dates' | 'discover' | 'plan' | 'budget';
export type AppStage = 'login' | 'groups' | 'group' | 'setup' | 'trip';

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  cardIds?: string[];
  suggestions?: AiSuggestion[];
  culture?: boolean;
}

// ── Change history (read-only; rows written by a DB trigger) ─────────────────

export interface ChangeEntry {
  id: string;
  table: string;
  action: 'insert' | 'update' | 'delete';
  who: UserId | null;
  summary?: string;
  changedFields: string[];
  at: string;
}

export interface HistoryApi {
  list(groupId: string): Promise<ChangeEntry[]>;
}
